[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["DATABASE_URL=\"postgresql://dummy:dummy@localhost:5432/dummy\" npm install --no-audit --no-fund"]

[phases.build]
cmds = [
  "npm install -D tsx",
  "DATABASE_URL=\"postgresql://dummy:dummy@localhost:5432/dummy\" npx prisma generate"
]

[start]
cmd = "npx tsx src/server.ts"