[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install --no-audit --no-fund"]

[phases.build]
cmds = [
  "npm install -D tsx",
  "npx prisma generate"
]

[start]
cmd = "npx tsx src/server.ts"