/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AquaAiRouteImport } from './routes/aqua-ai'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ImpactoRouteImport } from './routes/impacto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SobreRouteImport } from './routes/sobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AquaAiRoute = AquaAiRouteImport.update({
  id: '/aqua-ai',
  path: '/aqua-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactoRoute = ImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aqua-ai': typeof AquaAiRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/impacto': typeof ImpactoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/register': typeof RegisterRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aqua-ai': typeof AquaAiRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/impacto': typeof ImpactoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/register': typeof RegisterRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aqua-ai': typeof AquaAiRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/impacto': typeof ImpactoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/register': typeof RegisterRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aqua-ai'
    | '/como-funciona'
    | '/comunidade'
    | '/dashboard'
    | '/impacto'
    | '/login'
    | '/mapa'
    | '/register'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aqua-ai'
    | '/como-funciona'
    | '/comunidade'
    | '/dashboard'
    | '/impacto'
    | '/login'
    | '/mapa'
    | '/register'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aqua-ai'
    | '/como-funciona'
    | '/comunidade'
    | '/dashboard'
    | '/impacto'
    | '/login'
    | '/mapa'
    | '/register'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AquaAiRoute: typeof AquaAiRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DashboardRoute: typeof DashboardRoute
  ImpactoRoute: typeof ImpactoRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  RegisterRoute: typeof RegisterRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aqua-ai': {
      id: '/aqua-ai'
      path: '/aqua-ai'
      fullPath: '/aqua-ai'
      preLoaderRoute: typeof AquaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacto': {
      id: '/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof ImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AquaAiRoute: AquaAiRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ComunidadeRoute: ComunidadeRoute,
  DashboardRoute: DashboardRoute,
  ImpactoRoute: ImpactoRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  RegisterRoute: RegisterRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
